version: "3.9"

services:
  backend:
    image: main-service
    container_name: main-service
    restart: always
    ports:
      - "2020:2020"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 2020
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - db_data:/var/lib/postgresql/data

  backend2:
    image: trainer-workload
    container_name: trainer-workload
    restart: always
    ports:
      - "2025:2025"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 2025
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_DB: admin
      SPRING_ACTIVEMQ_BROKER_URL: tcp://localhost:61616

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    container_name: 531527c83ef0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

  activemq:
    image: apache/activemq-artemis
    container_name: 2aa863856977
    platform: linux/amd64
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

volumes:
  db_data: {}
  data: {}
