spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:datainit.sql
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] - %msg%n"

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

server:
  port: 9091


brute-force:
  attempt:
    count: 3

web:
  cors:
    allowed-origins:
      - "http://localhost:9091"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    max-age: 86400
    allowed-headers:
      - "Origin"
      - "X-Api-Key"
      - "X-Requested-With"
      - "Content-Type"
      - "Accept"
      - "Authorization"
    exposed-headers:
      - "X-Get-Header"
