server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stg
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:properties/datainit.sql
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] - %msg%n"

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351