server:
  port: 9296

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ainazzzzz/Config-server.git
          clone-on-start: true


